stages:
  - install
  - build
  - deploy

# 下载依赖
install:
  stage: install
  image: node:12
  cache:
    key: cache
    paths:
      - node_modules/
  script:
    - yarn install
  only:
    - master
    - dev
    - /^release-([0-9]{1,3})\.([0-9]{1,3})\.([0-9]{1,3})$/

# 打包
.build:
  stage: build
  image: node:12
  cache:
    key: cache
    paths:
      - node_modules/
  artifacts:
    paths:
      - dist
    expire_in: 1 day

build-master:
  extends: .build
  script:
    - yarn build
  environment:
    name: master
  only:
    - master

build-dev:
  extends: .build
  script:
     - yarn build
  environment:
    name: staging/dev
  only:
    - dev

build-release:
  extends: .build
  script:
    - yarn build
  environment:
    name: staging/release
  only:
    - /^release-([0-9]{1,3})\.([0-9]{1,3})\.([0-9]{1,3})$/

# 上传又拍云
.deploy:
  stage: deploy
  image: registry-vpc.cn-hangzhou.aliyuncs.com/mainto_micro/environment-node:10-deploy
  script:
    - PROJECT_DIR=`pwd`
    - cd /deploy-scripts && yarn run deploy-upyun $DEPLOY_UPYUN_OPERATOR $DEPLOY_UPYUN_PASSWORD $DEPLOY_UPYUN_BUCKET $DEPLOY_UPYUN_PATH $PROJECT_DIR/$SOURCE_FOLDER $DEPLOY_UPYUN_URL
  retry: 2
  artifacts:
    paths:
      - dist
    expire_in: 1 day

    
deploy-master:
  extends: .deploy
  environment:
    name: master
  only:
    - master

deploy-dev:
  extends: .deploy
  environment:
    name: staging/dev
  only:
    - dev

deploy-release:
  extends: .deploy
  environment:
    name: staging/release
  only:
    - /^release-([0-9]{1,3})\.([0-9]{1,3})\.([0-9]{1,3})$/
